# File              : config.example.yaml
# Author            : Iman Tabrizian <iman.tabrizian@gmail.com>
# Date              : 01.04.2019
# Last Modified Date: 03.04.2019
# Last Modified By  : Iman Tabrizian <iman.tabrizian@gmail.com>

auth:
  username: <username>
  password: <password>
  region: <region>
  url: <url>
  project: <project>

vm:
  image: <image-to-use>
  network: <network-to-use>
  secgroup: <secgroup-to-use>
  flavor: <flavor-to-use>

prometheus: <prometheus-server>
ryu: <ryu-controller-url>
