# File              : topology.yaml
# Author            : Iman Tabrizian <iman.tabrizian@gmail.com>
# Date              : 08.04.2019
# Last Modified Date: 10.04.2019
# Last Modified By  : Iman Tabrizian <iman.tabrizian@gmail.com>

sw1:
  - endpoint: h1
    ip: 192.168.200.10
  - endpoint: sw2

sw2:
  - endpoint: h2
    ip: 192.168.200.100
