# File              : vnfs.yaml
# Author            : Iman Tabrizian <iman.tabrizian@gmail.com>
# Date              : 23.04.2019
# Last Modified Date: 18.06.2019
# Last Modified By  : Iman Tabrizian <iman.tabrizian@gmail.com>

snort:
  image: networkfunction/firewall
  location: h4.tr1


